# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1444146096);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1444146216);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444145398);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1444145606);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20150824130139");
user_pref("browser.startup.homepage_override.mstone", "25.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":0}");
user_pref("browser.taskbar.lastgroupid", "3E917604E7C33D56");
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-de@palemoon.org\":{\"version\":\"25.6.1\",\"type\":\"locale\",\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\langpack-de@palemoon.org.xpi\"},\"uMatrix@raymondhill.net\":{\"version\":\"0.9.2.1\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\uMatrix@raymondhill.net.xpi\"},\"uBlock0@raymondhill.net\":{\"version\":\"1.1.1\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\uBlock0@raymondhill.net.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B73a6fe31-595d-460b-a920-fcc0f8843232%7D:2.6.9.37");
user_pref("extensions.installCache", "[{\"name\":\"app-profile\",\"addons\":{\"langpack-de@palemoon.org\":{\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\langpack-de@palemoon.org.xpi\",\"mtime\":1444145531967},\"uBlock0@raymondhill.net\":{\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\uBlock0@raymondhill.net.xpi\",\"mtime\":1444145584047},\"uMatrix@raymondhill.net\":{\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\uMatrix@raymondhill.net.xpi\",\"mtime\":1444145566923},\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":{\"descriptor\":\"C:\\\\Users\\\\hinzmr\\\\AppData\\\\Roaming\\\\Moonchild Productions\\\\Pale Moon\\\\Profiles\\\\profile.default\\\\extensions\\\\{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi\",\"mtime\":1444145828195}}}]");
user_pref("extensions.lastAppVersion", "25.7.0");
user_pref("extensions.lastPlatformVersion", "25.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.ublock0.legacyToolbarButtonAdded", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.service.hidden", true);
user_pref("extensions.umatrix.legacyToolbarButtonAdded", true);
user_pref("extensions.umatrix.placeholderBackground", "linear-gradient(0deg,rgba(0,0,0,0.02) 25%,rgba(0,0,0,0.05) 25%,rgba(0,0,0,0.05) 75%,rgba(0,0,0,0.02) 75%,rgba(0,0,0,0.02)) center center / 10px 10px repeat scroll,linear-gradient(90deg,rgba(0,0,0,0.02) 25%,rgba(0,0,0,0.05) 25%,rgba(0,0,0,0.05) 75%,rgba(0,0,0,0.02) 75%,rgba(0,0,0,0.02)) center center / 10px 10px repeat scroll #fff");
user_pref("extensions.umatrix.placeholderBorder", "1px solid rgba(0, 0, 0, 0.05)");
user_pref("extensions.umatrix.placeholderDocument", "<html><head><meta charset=\"utf-8\"><style>body { background: {{bg}};color: gray;font: 12px sans-serif;margin: 0;overflow: hidden;padding: 2px;white-space: nowrap;}a { color: inherit;padding: 0 3px;text-decoration: none;}</style></head><body><a href=\"{{url}}\" title=\"{{url}}\" target=\"_blank\">&#x2191;</a>{{url}}</body></html>");
user_pref("extensions.umatrix.placeholderImage", "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==");
user_pref("gecko.buildID", "20150824130139");
user_pref("gecko.mstone", "25.7.0");
user_pref("general.useragent.site_specific_overrides", false);
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.gtemp", "");
user_pref("noscript.options.tabSelectedIndexes", "5,0,0");
user_pref("noscript.policynames", "");
user_pref("noscript.subscription.lastCheck", 1036974709);
user_pref("noscript.temp", "");
user_pref("noscript.version", "2.6.9.37");
user_pref("noscript.visibleUIChecked", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("plugins.notifyMissingFlash", false);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.cpd.cookies", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.lastversion", "1.26.0");
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("shumway.disabled", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("toolkit.startup.last_success", 1444145975);
user_pref("toolkit.telemetry.previousBuildID", "20150824130139");
user_pref("xpinstall.whitelist.add", "");
